"""Initial migration.

Revision ID: 6bd36c6da61f
Revises: 
Create Date: 2024-06-13 18:33:04.931056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd36c6da61f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Actors',
    sa.Column('ActorID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('BirthYear', sa.Integer(), nullable=True),
    sa.Column('Nationality', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ActorID')
    )
    op.create_table('Directors',
    sa.Column('DirectorID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('BirthYear', sa.Integer(), nullable=True),
    sa.Column('Nationality', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('DirectorID')
    )
    op.create_table('Movies',
    sa.Column('MovieID', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(), nullable=False),
    sa.Column('ReleaseYear', sa.Integer(), nullable=True),
    sa.Column('Genre', sa.String(), nullable=True),
    sa.Column('Rating', sa.Float(), nullable=True),
    sa.Column('DirectorID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['DirectorID'], ['Directors.DirectorID'], ),
    sa.PrimaryKeyConstraint('MovieID')
    )
    op.create_table('MovieActor',
    sa.Column('MovieID', sa.Integer(), nullable=False),
    sa.Column('ActorID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ActorID'], ['Actors.ActorID'], ),
    sa.ForeignKeyConstraint(['MovieID'], ['Movies.MovieID'], ),
    sa.PrimaryKeyConstraint('MovieID', 'ActorID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MovieActor')
    op.drop_table('Movies')
    op.drop_table('Directors')
    op.drop_table('Actors')
    # ### end Alembic commands ###
